services:
  eudiw_issuer:
    image: ghcr.io/niscy-eudiw/eudi-srv-web-issuing-eudiw-py:latest
    container_name: eudiw_issuer
    ports:
      - "5000:5000"
    environment:
      FLASK_RUN_PORT: 5000
      SERVICE_URL: "http://127.0.0.1:5000/"
      #Container path
      TRUSTED_CAS_PATH: "/app/certs/CAs"
      LOG_PATH: "/app/log"
      EIDAS_NODE_URL: "https://preprod.issuer.eudiw.dev/EidasNode/"
      DYNAMIC_PRESENTATION_URL: "https://dev.verifier-backend.eudiw.dev/ui/presentations/"

    # local path : container path
    volumes:
      - ./CAs:/app/certs/CAs
