services:
  eudiw_issuer:
    image: issuer_test:0.1
    container_name: eudiw_issuer
    ports:
      - "5000:5000"
    environment:
      FLASK_RUN_PORT: 5000
      FLASK_APP: "/app/__init__"
      SERVICE_URL: "http://127.0.0.1:5000/"
      #Container path
      TRUSTED_CAS_PATH: "/app/certs/CAs"
      PRIVKEY_PATH: "/app/privKeys"
      LOG_PATH: "/app/log"
      EIDAS_NODE_URL: "https://preprod.issuer.eudiw.dev/EidasNode/"
      DYNAMIC_PRESENTATION_URL: "https://dev.verifier-backend.eudiw.dev/ui/presentations/"
      EIDASNODE_LIGHT_SECRET:
      REVOCATION_API_KEY:
      REVOCATION_SERVICE_URL: 
      NOUNCE_KEY:
      WALLET_TEST_URL:
      

    # local path : container path
    volumes:
      - /etc/eudiw/pid-issuer/cert:/app/certs/CAs
      - /etc/eudiw/pid-issuer/privKey:/app/privKeys
